site_name: Ops Automation Docs
site_description: Suite de herramientas DevOps centralizada
theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]  # Te dice a MkDocs donde buscar tu codigo

nav:
  - Home: index.md
  - User Guide:
      - Configuration: index.md # Si decides expandir el README
  - Technical Reference:
      - Core Logging: reference/logging.md
      - AWS Module: reference/aws.md
      - Monitoring Module: reference/monitoring.md

