aws:
  snapshots:
    retention_days: 30
    dry_run: true
    regions:
      - us-east-1
    # ¡NUEVO! Solo permite correr en estas cuentas (Pon tu ID de AWS real aquí)
    allowed_account_ids:
      - "123456789012"
